services:

  postgres:
    image: postgres:13.9-alpine3.17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense-tracking-db

  unit-test:
    &unit-test
    build:
      context: .
      dockerfile: Dockerfile.test
    command: sh -c "sleep 3 && go test -v ./..."
    environment:
      - AUTHORIZATION_KEY=November 10, 2009
      - CGO_ENABLED=0
      - PORT=2565
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/expense-tracking-db?sslmode=disable
    depends_on:
      - postgres

  integration-test:
    <<: *unit-test
    command: sh -c  "sleep 3 && go test -v --tags=integration"
