services:
  postgres:
    image: postgres:13.9-alpine3.17
    environment:
      POSTGRES_PASSWORD: iOPXeR1wYsEIybr4lTUrtbBy
      POSTGRES_DB: expense-tracking-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  go:
    build: .
    command: sh -c "sleep 3 && /app/server"
    ports:
      - 2565:2565
    environment:
      - AUTHORIZATION_KEY=November 10, 2009
      - CGO_ENABLED=0
      - PORT=2565
      - DATABASE_URL=postgres://postgres:iOPXeR1wYsEIybr4lTUrtbBy@postgres:5432/expense-tracking-db?sslmode=disable
    depends_on:
      - postgres
